name: chater
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.1
  cloud_functions: ^4.6.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  firebase_database: ^10.3.8
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.5.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.8
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  image_picker: ^1.0.4
  intl: ^0.18.1
  path: ^1.8.3
  shared_preferences: ^2.2.2
  uuid: ^4.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
